(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["default~form-demo-form-demo-module-ngfactory~form-errors-demo-form-errors-demo-module-ngfactory~save~e0a5abde"],{

/***/ "../../node_modules/@angular/material/chips/typings/index.ngfactory.js":
/*!************************************************************************************************************!*\
  !*** C:/workspace/prosoft-components-demo/node_modules/@angular/material/chips/typings/index.ngfactory.js ***!
  \************************************************************************************************************/
/*! exports provided: MatChipsModuleNgFactory, RenderType_MatChipList, View_MatChipList_0, View_MatChipList_Host_0, MatChipListNgFactory */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "MatChipsModuleNgFactory", function() { return MatChipsModuleNgFactory; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "RenderType_MatChipList", function() { return RenderType_MatChipList; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "View_MatChipList_0", function() { return View_MatChipList_0; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "View_MatChipList_Host_0", function() { return View_MatChipList_Host_0; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "MatChipListNgFactory", function() { return MatChipListNgFactory; });
/* harmony import */ var _angular_core__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @angular/core */ "../../node_modules/@angular/core/fesm2015/core.js");
/* harmony import */ var _angular_material_chips__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! @angular/material/chips */ "../../node_modules/@angular/material/esm2015/chips.js");
/* harmony import */ var _angular_material_core__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! @angular/material/core */ "../../node_modules/@angular/material/esm2015/core.js");
/* harmony import */ var _angular_cdk_keycodes__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! @angular/cdk/keycodes */ "../../node_modules/@angular/cdk/esm2015/keycodes.js");
/* harmony import */ var _angular_material_form_field__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! @angular/material/form-field */ "../../node_modules/@angular/material/esm2015/form-field.js");
/* harmony import */ var _angular_cdk_bidi__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! @angular/cdk/bidi */ "../../node_modules/@angular/cdk/esm2015/bidi.js");
/* harmony import */ var _angular_forms__WEBPACK_IMPORTED_MODULE_6__ = __webpack_require__(/*! @angular/forms */ "../../node_modules/@angular/forms/fesm2015/forms.js");
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 







var MatChipsModuleNgFactory = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵcmf"](_angular_material_chips__WEBPACK_IMPORTED_MODULE_1__["MatChipsModule"], [], function (_l) { return _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmod"]([_angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](512, _angular_core__WEBPACK_IMPORTED_MODULE_0__["ComponentFactoryResolver"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵCodegenComponentFactoryResolver"], [[8, []], [3, _angular_core__WEBPACK_IMPORTED_MODULE_0__["ComponentFactoryResolver"]], _angular_core__WEBPACK_IMPORTED_MODULE_0__["NgModuleRef"]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](4608, _angular_material_core__WEBPACK_IMPORTED_MODULE_2__["ErrorStateMatcher"], _angular_material_core__WEBPACK_IMPORTED_MODULE_2__["ErrorStateMatcher"], []), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](1073742336, _angular_material_chips__WEBPACK_IMPORTED_MODULE_1__["MatChipsModule"], _angular_material_chips__WEBPACK_IMPORTED_MODULE_1__["MatChipsModule"], []), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](256, _angular_material_chips__WEBPACK_IMPORTED_MODULE_1__["MAT_CHIPS_DEFAULT_OPTIONS"], { separatorKeyCodes: [_angular_cdk_keycodes__WEBPACK_IMPORTED_MODULE_3__["ENTER"]] }, [])]); });

var styles_MatChipList = [".mat-chip{position:relative;overflow:hidden;box-sizing:border-box;-webkit-tap-highlight-color:transparent;transform:translateZ(0)}.mat-standard-chip{transition:box-shadow 280ms cubic-bezier(.4,0,.2,1);display:inline-flex;padding:7px 12px;border-radius:16px;align-items:center;cursor:default;min-height:32px;height:1px}._mat-animation-noopable.mat-standard-chip{transition:none;animation:none}.mat-standard-chip .mat-chip-remove.mat-icon{width:18px;height:18px}.mat-standard-chip::after{top:0;left:0;right:0;bottom:0;position:absolute;border-radius:inherit;opacity:0;content:'';pointer-events:none;transition:opacity .2s cubic-bezier(.35,0,.25,1)}.mat-standard-chip:hover::after{opacity:.12}.mat-standard-chip:focus{outline:0}.mat-standard-chip:focus::after{opacity:.16}@media (-ms-high-contrast:active){.mat-standard-chip{outline:solid 1px}.mat-standard-chip:focus{outline:dotted 2px}}.mat-standard-chip.mat-chip-disabled::after{opacity:0}.mat-standard-chip.mat-chip-disabled .mat-chip-remove,.mat-standard-chip.mat-chip-disabled .mat-chip-trailing-icon{cursor:default}.mat-standard-chip.mat-chip-with-avatar,.mat-standard-chip.mat-chip-with-trailing-icon.mat-chip-with-avatar{padding-top:0;padding-bottom:0}.mat-standard-chip.mat-chip-with-trailing-icon.mat-chip-with-avatar{padding-right:8px;padding-left:0}[dir=rtl] .mat-standard-chip.mat-chip-with-trailing-icon.mat-chip-with-avatar{padding-left:8px;padding-right:0}.mat-standard-chip.mat-chip-with-trailing-icon{padding-top:7px;padding-bottom:7px;padding-right:8px;padding-left:12px}[dir=rtl] .mat-standard-chip.mat-chip-with-trailing-icon{padding-left:8px;padding-right:12px}.mat-standard-chip.mat-chip-with-avatar{padding-left:0;padding-right:12px}[dir=rtl] .mat-standard-chip.mat-chip-with-avatar{padding-right:0;padding-left:12px}.mat-standard-chip .mat-chip-avatar{width:24px;height:24px;margin-right:8px;margin-left:4px}[dir=rtl] .mat-standard-chip .mat-chip-avatar{margin-left:8px;margin-right:4px}.mat-standard-chip .mat-chip-remove,.mat-standard-chip .mat-chip-trailing-icon{width:18px;height:18px;cursor:pointer}.mat-standard-chip .mat-chip-remove,.mat-standard-chip .mat-chip-trailing-icon{margin-left:8px;margin-right:0}[dir=rtl] .mat-standard-chip .mat-chip-remove,[dir=rtl] .mat-standard-chip .mat-chip-trailing-icon{margin-right:8px;margin-left:0}.mat-chip-list-wrapper{display:flex;flex-direction:row;flex-wrap:wrap;align-items:center;margin:-4px}.mat-chip-list-wrapper .mat-standard-chip,.mat-chip-list-wrapper input.mat-input-element{margin:4px}.mat-chip-list-stacked .mat-chip-list-wrapper{flex-direction:column;align-items:flex-start}.mat-chip-list-stacked .mat-chip-list-wrapper .mat-standard-chip{width:100%}.mat-chip-avatar{border-radius:50%;justify-content:center;align-items:center;display:flex;overflow:hidden;object-fit:cover}input.mat-chip-input{width:150px;margin:4px;flex:1 0 150px}"];
var RenderType_MatChipList = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵcrt"]({ encapsulation: 2, styles: styles_MatChipList, data: {} });

function View_MatChipList_0(_l) { return _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵvid"](2, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵeld"](0, 0, null, null, 1, "div", [["class", "mat-chip-list-wrapper"]], null, null, null, null, null)), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵncd"](null, 0)], null, null); }
function View_MatChipList_Host_0(_l) { return _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵvid"](0, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵeld"](0, 0, null, null, 3, "mat-chip-list", [["class", "mat-chip-list"]], [[1, "tabindex", 0], [1, "aria-describedby", 0], [1, "aria-required", 0], [1, "aria-disabled", 0], [1, "aria-invalid", 0], [1, "aria-multiselectable", 0], [1, "role", 0], [2, "mat-chip-list-disabled", null], [2, "mat-chip-list-invalid", null], [2, "mat-chip-list-required", null], [1, "aria-orientation", 0], [8, "id", 0]], [[null, "focus"], [null, "blur"], [null, "keydown"]], function (_v, en, $event) { var ad = true; if (("focus" === en)) {
        var pd_0 = (_angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2).focus() !== false);
        ad = (pd_0 && ad);
    } if (("blur" === en)) {
        var pd_1 = (_angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2)._blur() !== false);
        ad = (pd_1 && ad);
    } if (("keydown" === en)) {
        var pd_2 = (_angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2)._keydown($event) !== false);
        ad = (pd_2 && ad);
    } return ad; }, View_MatChipList_0, RenderType_MatChipList)), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵprd"](6144, null, _angular_material_form_field__WEBPACK_IMPORTED_MODULE_4__["MatFormFieldControl"], null, [_angular_material_chips__WEBPACK_IMPORTED_MODULE_1__["MatChipList"]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵdid"](2, 1556480, null, 1, _angular_material_chips__WEBPACK_IMPORTED_MODULE_1__["MatChipList"], [_angular_core__WEBPACK_IMPORTED_MODULE_0__["ElementRef"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["ChangeDetectorRef"], [2, _angular_cdk_bidi__WEBPACK_IMPORTED_MODULE_5__["Directionality"]], [2, _angular_forms__WEBPACK_IMPORTED_MODULE_6__["NgForm"]], [2, _angular_forms__WEBPACK_IMPORTED_MODULE_6__["FormGroupDirective"]], _angular_material_core__WEBPACK_IMPORTED_MODULE_2__["ErrorStateMatcher"], [8, null]], null, null), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵqud"](603979776, 1, { chips: 1 })], function (_ck, _v) { _ck(_v, 2, 0); }, function (_ck, _v) { var currVal_0 = (_angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2).disabled ? null : _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2)._tabIndex); var currVal_1 = (_angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2)._ariaDescribedby || null); var currVal_2 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2).required.toString(); var currVal_3 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2).disabled.toString(); var currVal_4 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2).errorState; var currVal_5 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2).multiple; var currVal_6 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2).role; var currVal_7 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2).disabled; var currVal_8 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2).errorState; var currVal_9 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2).required; var currVal_10 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2).ariaOrientation; var currVal_11 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2)._uid; _ck(_v, 0, 1, [currVal_0, currVal_1, currVal_2, currVal_3, currVal_4, currVal_5, currVal_6, currVal_7, currVal_8, currVal_9, currVal_10, currVal_11]); }); }
var MatChipListNgFactory = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵccf"]("mat-chip-list", _angular_material_chips__WEBPACK_IMPORTED_MODULE_1__["MatChipList"], View_MatChipList_Host_0, { errorStateMatcher: "errorStateMatcher", multiple: "multiple", compareWith: "compareWith", value: "value", required: "required", placeholder: "placeholder", disabled: "disabled", ariaOrientation: "aria-orientation", selectable: "selectable", tabIndex: "tabIndex" }, { change: "change", valueChange: "valueChange" }, ["*"]);



/***/ }),

/***/ "../components/form-base/index.ts":
/*!****************************************!*\
  !*** ../components/form-base/index.ts ***!
  \****************************************/
/*! exports provided: PsFormBaseModule, BasePsFormService, PsFormService, hasRequiredField */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var _public_api__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./public_api */ "../components/form-base/public_api.ts");
/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "PsFormBaseModule", function() { return _public_api__WEBPACK_IMPORTED_MODULE_0__["PsFormBaseModule"]; });

/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "BasePsFormService", function() { return _public_api__WEBPACK_IMPORTED_MODULE_0__["BasePsFormService"]; });

/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "PsFormService", function() { return _public_api__WEBPACK_IMPORTED_MODULE_0__["PsFormService"]; });

/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "hasRequiredField", function() { return _public_api__WEBPACK_IMPORTED_MODULE_0__["hasRequiredField"]; });

// export what ./public_api exports so we can import with the lib name like this:
// import { ModuleA } from 'libname'



/***/ }),

/***/ "../components/form-base/public_api.ts":
/*!*********************************************!*\
  !*** ../components/form-base/public_api.ts ***!
  \*********************************************/
/*! exports provided: PsFormBaseModule, BasePsFormService, PsFormService, hasRequiredField */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var _src_form_base_module__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./src/form-base.module */ "../components/form-base/src/form-base.module.ts");
/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "PsFormBaseModule", function() { return _src_form_base_module__WEBPACK_IMPORTED_MODULE_0__["PsFormBaseModule"]; });

/* harmony import */ var _src_form_service__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./src/form.service */ "../components/form-base/src/form.service.ts");
/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "BasePsFormService", function() { return _src_form_service__WEBPACK_IMPORTED_MODULE_1__["BasePsFormService"]; });

/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "PsFormService", function() { return _src_form_service__WEBPACK_IMPORTED_MODULE_1__["PsFormService"]; });

/* harmony import */ var _src_helpers__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./src/helpers */ "../components/form-base/src/helpers.ts");
/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "hasRequiredField", function() { return _src_helpers__WEBPACK_IMPORTED_MODULE_2__["hasRequiredField"]; });






/***/ }),

/***/ "../components/form-base/src/form-base.module.ts":
/*!*******************************************************!*\
  !*** ../components/form-base/src/form-base.module.ts ***!
  \*******************************************************/
/*! exports provided: PsFormBaseModule */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "PsFormBaseModule", function() { return PsFormBaseModule; });
/* harmony import */ var _angular_core__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @angular/core */ "../../node_modules/@angular/core/fesm2015/core.js");
/* harmony import */ var _form_service__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./form.service */ "../components/form-base/src/form.service.ts");


class PsFormBaseModule {
    static forRoot(formsServiceType) {
        return {
            ngModule: PsFormBaseModule,
            providers: [{ provide: _form_service__WEBPACK_IMPORTED_MODULE_1__["PsFormService"], useClass: formsServiceType }],
        };
    }
}


/***/ }),

/***/ "../components/form-base/src/form.service.ts":
/*!***************************************************!*\
  !*** ../components/form-base/src/form.service.ts ***!
  \***************************************************/
/*! exports provided: PsFormService, BasePsFormService */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "PsFormService", function() { return PsFormService; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "BasePsFormService", function() { return BasePsFormService; });
/* harmony import */ var _angular_forms__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @angular/forms */ "../../node_modules/@angular/forms/fesm2015/forms.js");
/* harmony import */ var _prosoft_components_utils__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! @prosoft/components/utils */ "../components/utils/index.ts");
/* harmony import */ var rxjs__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! rxjs */ "../../node_modules/rxjs/_esm2015/index.js");
/* harmony import */ var rxjs_operators__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! rxjs/operators */ "../../node_modules/rxjs/_esm2015/operators/index.js");
/* harmony import */ var _helpers__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ./helpers */ "../components/form-base/src/helpers.ts");





class PsFormService {
}
class BasePsFormService extends PsFormService {
    constructor() {
        super(...arguments);
        this.options = {
            debounceTime: 100,
            includeControlsDefault: false,
        };
        this.tryDetectRequired = true;
        this.getControlType = _helpers__WEBPACK_IMPORTED_MODULE_4__["getControlType"];
    }
    getControlErrors(control) {
        return this.getErrors(control, true, 'control');
    }
    getFormErrors(form, includeControls) {
        if (includeControls == null) {
            includeControls = this.options.includeControlsDefault;
        }
        return this.getErrors(form, includeControls, 'form');
    }
    /**
     * Provided to be overwritten to filter the errors.
     */
    filterErrors(errorData, includeControls, source) {
        return Object(rxjs__WEBPACK_IMPORTED_MODULE_2__["of"])(errorData);
    }
    getErrors(control, includeControls, source) {
        const update$ = this.createUpdateTrigger(control);
        return update$.pipe(Object(rxjs_operators__WEBPACK_IMPORTED_MODULE_3__["map"])(() => this.getErrorInfo(control, includeControls)), Object(rxjs_operators__WEBPACK_IMPORTED_MODULE_3__["switchMap"])(errorData => this.filterErrors(errorData, includeControls, source)), Object(rxjs_operators__WEBPACK_IMPORTED_MODULE_3__["switchMap"])(errorData => this.mapDataToError(errorData)));
    }
    createUpdateTrigger(control) {
        return Object(rxjs__WEBPACK_IMPORTED_MODULE_2__["merge"])(control.valueChanges, control.statusChanges).pipe(Object(rxjs_operators__WEBPACK_IMPORTED_MODULE_3__["startWith"])(null), Object(rxjs_operators__WEBPACK_IMPORTED_MODULE_3__["debounceTime"])(this.options.debounceTime));
    }
    getErrorInfo(control, includeControls = false) {
        return this.getControlErrorInfoInternal(control, '', includeControls);
    }
    getControlErrorInfoInternal(control, controlPath, includeControls) {
        const errors = [];
        if (control instanceof _angular_forms__WEBPACK_IMPORTED_MODULE_0__["FormGroup"] || control instanceof _angular_forms__WEBPACK_IMPORTED_MODULE_0__["FormArray"]) {
            for (const childName in control.controls) {
                if (!control.controls.hasOwnProperty(childName)) {
                    continue;
                }
                const childControl = control.controls[childName];
                if (!(childControl instanceof _angular_forms__WEBPACK_IMPORTED_MODULE_0__["FormControl"]) || includeControls) {
                    errors.push(...this.getControlErrorInfoInternal(childControl, controlPath ? controlPath + '.' + childName : childName, includeControls));
                }
            }
        }
        if (control.errors) {
            errors.push(...Object(_prosoft_components_utils__WEBPACK_IMPORTED_MODULE_1__["objectToKeyValueArray"])(control.errors).map(error => this.createFormErrorData(error, control, controlPath)));
        }
        return errors;
    }
    createFormErrorData(error, control, controlPath) {
        return {
            controlPath: controlPath,
            errorKey: error.key,
            errorValue: error.value,
            isControl: control instanceof _angular_forms__WEBPACK_IMPORTED_MODULE_0__["FormControl"],
        };
    }
}


/***/ }),

/***/ "../components/form-base/src/helpers.ts":
/*!**********************************************!*\
  !*** ../components/form-base/src/helpers.ts ***!
  \**********************************************/
/*! exports provided: hasRequiredField, getControlType */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "hasRequiredField", function() { return hasRequiredField; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "getControlType", function() { return getControlType; });
/* harmony import */ var _angular_forms__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @angular/forms */ "../../node_modules/@angular/forms/fesm2015/forms.js");

function hasRequiredField(abstractControl) {
    if (abstractControl.validator) {
        const validator = abstractControl.validator({});
        if (validator && validator.required) {
            return true;
        }
    }
    if (abstractControl instanceof _angular_forms__WEBPACK_IMPORTED_MODULE_0__["FormGroup"] || abstractControl instanceof _angular_forms__WEBPACK_IMPORTED_MODULE_0__["FormArray"]) {
        const controls = abstractControl.controls; // any because of https://github.com/microsoft/TypeScript/issues/32552
        for (const controlName in controls) {
            if (controls[controlName]) {
                if (hasRequiredField(controls[controlName])) {
                    return true;
                }
            }
        }
    }
    return false;
}
/**
 * Returns the type of the control. Most of the time the type is the same as the selector.
 *
 * @param control The control class (MatSlider, MatSelect, ...)
 */
function getControlType(control) {
    const controlId = control.id /* MatFormFieldControl, z.B. checkbox */ || control.name; /* mat-radio-group */
    if (controlId) {
        const parts = controlId.split('-');
        if (parts[parts.length - 1].match(/[0-9]/)) {
            parts.pop();
        }
        return parts.join('-');
    }
    if (control.step !== undefined && control.thumbLabel !== undefined) {
        return 'mat-slider';
    }
    return null;
}


/***/ }),

/***/ "../components/form-errors/src/form-errors.component.ngfactory.js":
/*!************************************************************************!*\
  !*** ../components/form-errors/src/form-errors.component.ngfactory.js ***!
  \************************************************************************/
/*! exports provided: RenderType_PsFormErrorsComponent, View_PsFormErrorsComponent_0, View_PsFormErrorsComponent_Host_0, PsFormErrorsComponentNgFactory */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "RenderType_PsFormErrorsComponent", function() { return RenderType_PsFormErrorsComponent; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "View_PsFormErrorsComponent_0", function() { return View_PsFormErrorsComponent_0; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "View_PsFormErrorsComponent_Host_0", function() { return View_PsFormErrorsComponent_Host_0; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "PsFormErrorsComponentNgFactory", function() { return PsFormErrorsComponentNgFactory; });
/* harmony import */ var _angular_core__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @angular/core */ "../../node_modules/@angular/core/fesm2015/core.js");
/* harmony import */ var _angular_material_chips__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! @angular/material/chips */ "../../node_modules/@angular/material/esm2015/chips.js");
/* harmony import */ var _angular_cdk_platform__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! @angular/cdk/platform */ "../../node_modules/@angular/cdk/esm2015/platform.js");
/* harmony import */ var _angular_material_core__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! @angular/material/core */ "../../node_modules/@angular/material/esm2015/core.js");
/* harmony import */ var _angular_platform_browser_animations__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! @angular/platform-browser/animations */ "../../node_modules/@angular/platform-browser/fesm2015/animations.js");
/* harmony import */ var _node_modules_angular_material_chips_typings_index_ngfactory__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! ../../../../node_modules/@angular/material/chips/typings/index.ngfactory */ "../../node_modules/@angular/material/chips/typings/index.ngfactory.js");
/* harmony import */ var _angular_material_form_field__WEBPACK_IMPORTED_MODULE_6__ = __webpack_require__(/*! @angular/material/form-field */ "../../node_modules/@angular/material/esm2015/form-field.js");
/* harmony import */ var _angular_cdk_bidi__WEBPACK_IMPORTED_MODULE_7__ = __webpack_require__(/*! @angular/cdk/bidi */ "../../node_modules/@angular/cdk/esm2015/bidi.js");
/* harmony import */ var _angular_forms__WEBPACK_IMPORTED_MODULE_8__ = __webpack_require__(/*! @angular/forms */ "../../node_modules/@angular/forms/fesm2015/forms.js");
/* harmony import */ var _angular_common__WEBPACK_IMPORTED_MODULE_9__ = __webpack_require__(/*! @angular/common */ "../../node_modules/@angular/common/fesm2015/common.js");
/* harmony import */ var _form_errors_component__WEBPACK_IMPORTED_MODULE_10__ = __webpack_require__(/*! ./form-errors.component */ "../components/form-errors/src/form-errors.component.ts");
/* harmony import */ var _form_base_src_form_service__WEBPACK_IMPORTED_MODULE_11__ = __webpack_require__(/*! ../../form-base/src/form.service */ "../components/form-base/src/form.service.ts");
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 












var styles_PsFormErrorsComponent = ["\n      .ps-form-errors__container {\n        font-size: 12px;\n      }\n      .mat-chip.ps-form-errors__item {\n        background-color: var(--ps-error);\n        color: var(--ps-error-contrast);\n      }\n    "];
var RenderType_PsFormErrorsComponent = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵcrt"]({ encapsulation: 2, styles: styles_PsFormErrorsComponent, data: {} });

function View_PsFormErrorsComponent_2(_l) { return _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵvid"](0, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵeld"](0, 0, null, null, 5, "mat-chip", [["class", "ps-form-errors__item mat-chip"], ["role", "option"]], [[1, "tabindex", 0], [2, "mat-chip-selected", null], [2, "mat-chip-with-avatar", null], [2, "mat-chip-with-trailing-icon", null], [2, "mat-chip-disabled", null], [2, "_mat-animation-noopable", null], [1, "disabled", 0], [1, "aria-disabled", 0], [1, "aria-selected", 0]], [[null, "click"], [null, "keydown"], [null, "focus"], [null, "blur"]], function (_v, en, $event) { var ad = true; if (("click" === en)) {
        var pd_0 = (_angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 1)._handleClick($event) !== false);
        ad = (pd_0 && ad);
    } if (("keydown" === en)) {
        var pd_1 = (_angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 1)._handleKeydown($event) !== false);
        ad = (pd_1 && ad);
    } if (("focus" === en)) {
        var pd_2 = (_angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 1).focus() !== false);
        ad = (pd_2 && ad);
    } if (("blur" === en)) {
        var pd_3 = (_angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 1)._blur() !== false);
        ad = (pd_3 && ad);
    } return ad; }, null, null)), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵdid"](1, 147456, [[1, 4]], 3, _angular_material_chips__WEBPACK_IMPORTED_MODULE_1__["MatChip"], [_angular_core__WEBPACK_IMPORTED_MODULE_0__["ElementRef"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["NgZone"], _angular_cdk_platform__WEBPACK_IMPORTED_MODULE_2__["Platform"], [2, _angular_material_core__WEBPACK_IMPORTED_MODULE_3__["MAT_RIPPLE_GLOBAL_OPTIONS"]], [2, _angular_platform_browser_animations__WEBPACK_IMPORTED_MODULE_4__["ANIMATION_MODULE_TYPE"]]], null, null), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵqud"](603979776, 2, { avatar: 0 }), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵqud"](603979776, 3, { trailingIcon: 0 }), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵqud"](603979776, 4, { removeIcon: 0 }), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵted"](5, null, ["", ""]))], null, function (_ck, _v) { var currVal_0 = (_angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 1).disabled ? null : (0 - 1)); var currVal_1 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 1).selected; var currVal_2 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 1).avatar; var currVal_3 = (_angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 1).trailingIcon || _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 1).removeIcon); var currVal_4 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 1).disabled; var currVal_5 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 1)._animationsDisabled; var currVal_6 = (_angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 1).disabled || null); var currVal_7 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 1).disabled.toString(); var currVal_8 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 1).ariaSelected; _ck(_v, 0, 0, currVal_0, currVal_1, currVal_2, currVal_3, currVal_4, currVal_5, currVal_6, currVal_7, currVal_8); var currVal_9 = _v.context.$implicit.errorText; _ck(_v, 5, 0, currVal_9); }); }
function View_PsFormErrorsComponent_1(_l) { return _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵvid"](0, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵeld"](0, 0, null, null, 5, "mat-chip-list", [["class", "ps-form-errors__container mat-chip-list"]], [[1, "tabindex", 0], [1, "aria-describedby", 0], [1, "aria-required", 0], [1, "aria-disabled", 0], [1, "aria-invalid", 0], [1, "aria-multiselectable", 0], [1, "role", 0], [2, "mat-chip-list-disabled", null], [2, "mat-chip-list-invalid", null], [2, "mat-chip-list-required", null], [1, "aria-orientation", 0], [8, "id", 0]], [[null, "focus"], [null, "blur"], [null, "keydown"]], function (_v, en, $event) { var ad = true; if (("focus" === en)) {
        var pd_0 = (_angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2).focus() !== false);
        ad = (pd_0 && ad);
    } if (("blur" === en)) {
        var pd_1 = (_angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2)._blur() !== false);
        ad = (pd_1 && ad);
    } if (("keydown" === en)) {
        var pd_2 = (_angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2)._keydown($event) !== false);
        ad = (pd_2 && ad);
    } return ad; }, _node_modules_angular_material_chips_typings_index_ngfactory__WEBPACK_IMPORTED_MODULE_5__["View_MatChipList_0"], _node_modules_angular_material_chips_typings_index_ngfactory__WEBPACK_IMPORTED_MODULE_5__["RenderType_MatChipList"])), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵprd"](6144, null, _angular_material_form_field__WEBPACK_IMPORTED_MODULE_6__["MatFormFieldControl"], null, [_angular_material_chips__WEBPACK_IMPORTED_MODULE_1__["MatChipList"]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵdid"](2, 1556480, null, 1, _angular_material_chips__WEBPACK_IMPORTED_MODULE_1__["MatChipList"], [_angular_core__WEBPACK_IMPORTED_MODULE_0__["ElementRef"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["ChangeDetectorRef"], [2, _angular_cdk_bidi__WEBPACK_IMPORTED_MODULE_7__["Directionality"]], [2, _angular_forms__WEBPACK_IMPORTED_MODULE_8__["NgForm"]], [2, _angular_forms__WEBPACK_IMPORTED_MODULE_8__["FormGroupDirective"]], _angular_material_core__WEBPACK_IMPORTED_MODULE_3__["ErrorStateMatcher"], [8, null]], null, null), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵqud"](603979776, 1, { chips: 1 }), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵand"](16777216, null, 0, 1, null, View_PsFormErrorsComponent_2)), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵdid"](5, 278528, null, 0, _angular_common__WEBPACK_IMPORTED_MODULE_9__["NgForOf"], [_angular_core__WEBPACK_IMPORTED_MODULE_0__["ViewContainerRef"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["TemplateRef"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["IterableDiffers"]], { ngForOf: [0, "ngForOf"] }, null)], function (_ck, _v) { _ck(_v, 2, 0); var currVal_12 = _v.context.ngIf; _ck(_v, 5, 0, currVal_12); }, function (_ck, _v) { var currVal_0 = (_angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2).disabled ? null : _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2)._tabIndex); var currVal_1 = (_angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2)._ariaDescribedby || null); var currVal_2 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2).required.toString(); var currVal_3 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2).disabled.toString(); var currVal_4 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2).errorState; var currVal_5 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2).multiple; var currVal_6 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2).role; var currVal_7 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2).disabled; var currVal_8 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2).errorState; var currVal_9 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2).required; var currVal_10 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2).ariaOrientation; var currVal_11 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2)._uid; _ck(_v, 0, 1, [currVal_0, currVal_1, currVal_2, currVal_3, currVal_4, currVal_5, currVal_6, currVal_7, currVal_8, currVal_9, currVal_10, currVal_11]); }); }
function View_PsFormErrorsComponent_0(_l) { return _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵvid"](2, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵand"](16777216, null, null, 2, null, View_PsFormErrorsComponent_1)), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵdid"](1, 16384, null, 0, _angular_common__WEBPACK_IMPORTED_MODULE_9__["NgIf"], [_angular_core__WEBPACK_IMPORTED_MODULE_0__["ViewContainerRef"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["TemplateRef"]], { ngIf: [0, "ngIf"] }, null), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵpid"](131072, _angular_common__WEBPACK_IMPORTED_MODULE_9__["AsyncPipe"], [_angular_core__WEBPACK_IMPORTED_MODULE_0__["ChangeDetectorRef"]])], function (_ck, _v) { var _co = _v.component; var currVal_0 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵunv"](_v, 1, 0, _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵnov"](_v, 2).transform(_co.errors$)); _ck(_v, 1, 0, currVal_0); }, null); }
function View_PsFormErrorsComponent_Host_0(_l) { return _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵvid"](0, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵeld"](0, 0, null, null, 1, "ps-form-errors", [], null, null, null, View_PsFormErrorsComponent_0, RenderType_PsFormErrorsComponent)), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵdid"](1, 573440, null, 0, _form_errors_component__WEBPACK_IMPORTED_MODULE_10__["PsFormErrorsComponent"], [_form_base_src_form_service__WEBPACK_IMPORTED_MODULE_11__["PsFormService"]], null, null)], null, null); }
var PsFormErrorsComponentNgFactory = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵccf"]("ps-form-errors", _form_errors_component__WEBPACK_IMPORTED_MODULE_10__["PsFormErrorsComponent"], View_PsFormErrorsComponent_Host_0, { form: "form", includeControls: "includeControls" }, {}, []);



/***/ }),

/***/ "../components/form-errors/src/form-errors.component.ts":
/*!**************************************************************!*\
  !*** ../components/form-errors/src/form-errors.component.ts ***!
  \**************************************************************/
/*! exports provided: PsFormErrorsComponent */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "PsFormErrorsComponent", function() { return PsFormErrorsComponent; });
/* harmony import */ var _angular_core__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @angular/core */ "../../node_modules/@angular/core/fesm2015/core.js");
/* harmony import */ var _angular_forms__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! @angular/forms */ "../../node_modules/@angular/forms/fesm2015/forms.js");
/* harmony import */ var _prosoft_components_form_base__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! @prosoft/components/form-base */ "../components/form-base/index.ts");



class PsFormErrorsComponent {
    constructor(formErrorsService) {
        this.formErrorsService = formErrorsService;
        this.includeControls = null;
    }
    ngOnChanges() {
        this.errors$ = this.formErrorsService.getFormErrors(this.form, this.includeControls);
    }
}


/***/ }),

/***/ "../components/utils/index.ts":
/*!************************************!*\
  !*** ../components/utils/index.ts ***!
  \************************************/
/*! exports provided: objectToKeyValueArray */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var _public_api__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./public_api */ "../components/utils/public_api.ts");
/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "objectToKeyValueArray", function() { return _public_api__WEBPACK_IMPORTED_MODULE_0__["objectToKeyValueArray"]; });

// export what ./public_api exports so we can import with the lib name like this:
// import { ModuleA } from 'libname'



/***/ }),

/***/ "../components/utils/public_api.ts":
/*!*****************************************!*\
  !*** ../components/utils/public_api.ts ***!
  \*****************************************/
/*! exports provided: objectToKeyValueArray */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var _src_object__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./src/object */ "../components/utils/src/object.ts");
/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "objectToKeyValueArray", function() { return _src_object__WEBPACK_IMPORTED_MODULE_0__["objectToKeyValueArray"]; });




/***/ }),

/***/ "../components/utils/src/object.ts":
/*!*****************************************!*\
  !*** ../components/utils/src/object.ts ***!
  \*****************************************/
/*! exports provided: objectToKeyValueArray */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "objectToKeyValueArray", function() { return objectToKeyValueArray; });
function objectToKeyValueArray(errors) {
    const errorList = [];
    for (const key in errors) {
        if (!errors.hasOwnProperty(key)) {
            continue;
        }
        errorList.push({
            key: key,
            value: errors[key],
        });
    }
    return errorList;
}


/***/ })

}]);
//# sourceMappingURL=default~form-demo-form-demo-module-ngfactory~form-errors-demo-form-errors-demo-module-ngfactory~save~e0a5abde-es2015.js.map